'use client';
import { useCallback, useEffect, useState } from 'react';
import { BarChart3, Download, ExternalLink, Globe2, LockKeyhole, RefreshCw, Search, ShieldCheck, Users, Link2, ArrowUpRight, FileUp } from 'lucide-react';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Table, TableHeader, TableHead, TableBody, TableRow, TableCell } from '@/components/ui/table';
import { Empty, EmptyHeader, EmptyTitle, EmptyDescription, EmptyMedia } from '@/components/ui/empty';
type Metric = { appId: string; day: string; metric: string; source: string; value: number };
type AppInfo = { id: string; name: string; lastSync?: string; message?: string };
type Subscriber = { appId: string; id: string; name: string | null; product: string; environment: string; status: string; expiresAt: string; updatedAt: string };
type Connection = { configured: boolean; lastSync: string | null; message: string };
type Data = { apps: AppInfo[]; metrics: Metric[]; subscribers: Subscriber[]; connections: Record<string, Connection>; subscriberError?: string; subscriberFetchedAt?: string };
const blank: Data = { apps: [], metrics: [], subscribers: [], connections: {} };
const fmt = (v: number | undefined) => v === undefined ? '—' : v.toLocaleString();
function when(value?: string | null) { return value ? new Date(value).toLocaleString(undefined, { dateStyle: 'medium', timeStyle: 'short' }) : 'Not synced yet'; }
function Picker({ label, value, onChange, options }: { label: string; value: string; onChange: (v: string) => void; options: [string, string][] }) { return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue /></SelectTrigger><SelectContent>{options.map(([key, text]) => <SelectItem key={key} value={key}>{text}</SelectItem>)}</SelectContent></Select>; }
function NoData({ title, children }: { title: string; children: React.ReactNode }) { return <Empty><EmptyHeader><EmptyMedia variant="icon"><BarChart3 /></EmptyMedia><EmptyTitle>{title}</EmptyTitle><EmptyDescription>{children}</EmptyDescription></EmptyHeader></Empty>; }
export default function Dashboard() {
  const [data, setData] = useState<Data>(blank), [tab, setTab] = useState('overview'), [days, setDays] = useState('30');
  const [environment, setEnvironment] = useState('PRODUCTION'), [query, setQuery] = useState('');
  const [appId, setAppId] = useState('all');
  const [busy, setBusy] = useState(false), [message, setMessage] = useState(''), [loaded, setLoaded] = useState(false), [importing, setImporting] = useState(false);
  const load = useCallback(async () => { setBusy(true); try { const res = await fetch('/admin/getreep/api/dashboard', { cache:'no-store' }); const body = await res.json(); if (!res.ok) throw new Error(body.error || 'Could not load dashboard.'); setData(body); setMessage(''); setLoaded(true); } catch(e) { setMessage(e instanceof Error ? e.message : 'Could not load dashboard.'); } finally { setBusy(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => {
    const mc = (document as unknown as { modelContext?: { registerTool: (t: unknown, o: unknown) => unknown } }).modelContext;
    if (!mc) return; const lifecycle = new AbortController();
    try { void Promise.resolve(mc.registerTool({ name:'read_app_metrics', description:'Read aggregate metrics and connection status shown in AyNcode App Insights. Does not expose subscriber identities.', inputSchema:{type:'object',properties:{},additionalProperties:false}, annotations:{readOnlyHint:true,untrustedContentHint:true}, execute:(input:unknown) => { if(!input || typeof input!=='object' || Object.keys(input).length) throw new Error('No arguments expected.'); return {metrics:data.metrics,connections:data.connections}; } }, {signal:lifecycle.signal})).catch(()=>{}); } catch {} return ()=>lifecycle.abort();
  },[data]);
  const cutoff = new Date(); cutoff.setUTCDate(cutoff.getUTCDate()-Number(days)+1);
  const metrics = data.metrics.filter(r=>(appId==='all'||r.appId===appId)&&r.day>=cutoff.toISOString().slice(0,10)&&r.day<=new Date().toISOString().slice(0,10));
  const subscriberSupported = appId==='all'||appId==='6799787039';
  const total = (metric:string) => { const rows=metrics.filter(r=>r.metric===metric); return rows.length?rows.reduce((n,r)=>n+r.value,0):undefined; };
  const subscribers=data.subscribers.filter(s=>s.environment===environment&&`${s.name||''} ${s.id} ${s.product} ${s.status}`.toLowerCase().includes(query.toLowerCase()));
  const active=subscriberSupported&&data.connections.subscribers?.configured&&!data.subscriberError?data.subscribers.filter(s=>s.environment==='PRODUCTION'&&s.status==='Active access').length:undefined;
  const series=[...new Set(metrics.filter(r=>r.metric==='first_downloads').map(r=>r.day))].sort().map(day=>({day,count:metrics.filter(r=>r.day===day&&r.metric==='first_downloads').reduce((n,r)=>n+r.value,0)}));
  const channels=[...new Set(metrics.filter(r=>r.metric==='first_downloads').map(r=>r.source))].map(source=>({source,count:metrics.filter(r=>r.metric==='first_downloads'&&r.source===source).reduce((n,r)=>n+r.value,0)})).sort((a,b)=>b.count-a.count);
  async function syncApple() {
    setBusy(true);setMessage('Refreshing the Apple app list…');
    const headers={'X-CSRFToken':document.querySelector<HTMLMetaElement>('meta[name="csrf-token"]')?.content||''};
    try {
      const catalog=await fetch('/admin/getreep/api/sync/apps',{method:'POST',headers});const body=await catalog.json();
      if(!catalog.ok)throw new Error(body.error||'Could not load apps.');
      const apps:AppInfo[]=body.apps;
      const targets=appId==='all'?apps:apps.filter(a=>a.id===appId);
      if(!targets.length)throw new Error('No accessible apps to sync. Select All apps and refresh.');
      const results:string[]=[];
      for(const app of targets){
        setMessage(`Syncing ${app.name}…`);
        const r=await fetch('/admin/getreep/api/sync/apple',{method:'POST',headers:{...headers,'X-Insights-App':app.id}});
        const b=await r.json();results.push(`${app.name}: ${r.ok?b.message:b.error||'Sync failed'}`);
      }
      await load();setMessage(results.join(' • '));
    }catch(e){setMessage(e instanceof Error?e.message:'Apple sync failed.');}finally{setBusy(false);}
  }
  async function upload(file?:File) { if(!file)return;setImporting(true);try {if(appId==='all')throw new Error('Choose an individual app before importing.');if(file.size>2_000_000)throw new Error('Please use a CSV under 2 MB.'); const r=await fetch('/admin/getreep/api/import',{method:'POST',headers:{'Content-Type':'text/csv','X-Insights-App':appId,'X-CSRFToken':document.querySelector<HTMLMetaElement>('meta[name="csrf-token"]')?.content||''},body:await file.text()});const b=await r.json();if(!r.ok)throw new Error(b.error||'Import failed.');await load();setMessage(`Saved ${b.rows} daily measurements. Reimporting replaces the matching totals.`);}catch(e){setMessage(e instanceof Error?e.message:'Import failed.');}finally{setImporting(false);} }
  const cards=[{label:'First-time downloads',value:total('first_downloads'),detail:'New downloads · Apple',icon:Download},{label:'Product page views',value:total('page_views'),detail:'Listing views · Apple',icon:Search},{label:'Website page views',value:total('website_page_views'),detail:'Page loads · ayncode.com',icon:Globe2},{label:'Getreep Plus accounts',value:active,detail:'Getreep only · production access',icon:Users}];
  return <div className="app-shell"><header className="topbar"><a className="brand" href="/admin" aria-label="Back to AyNcode admin"><img className="brand-mark" src="/static/img/android-chrome-192.png" alt="" width="36" height="36"/>AyNcode<span className="brand-divider"/><span className="brand-sub">Insights</span></a><span className="private-label"><LockKeyhole size={14}/>Private workspace</span></header><main>
    <div className="page-heading"><div><p className="eyebrow">YOUR APPS, AT A GLANCE</p><h1>See how your apps grow.</h1><p className="subtitle">App Store discovery, website activity, and subscribers.</p></div><button className="button secondary" disabled={busy} onClick={()=>void load()} aria-label="Refresh dashboard"><RefreshCw size={16} className={busy?'spin':''}/>{busy?'Loading…':'Refresh'}</button></div>
    <div className="nav-row"><label>Application</label><Picker label="Application" value={appId} onChange={setAppId} options={[["all","All apps"],...data.apps.map(a=>[a.id,a.name] as [string,string])]}/></div>
    <Tabs value={tab} onValueChange={setTab}><div className="nav-row"><TabsList variant="line"><TabsTrigger value="overview"><BarChart3/>Overview</TabsTrigger><TabsTrigger value="subscribers"><Users/>Subscribers</TabsTrigger><TabsTrigger value="sources"><Link2/>Connections</TabsTrigger></TabsList>{tab==='overview'&&<Picker label="Reporting period" value={days} onChange={setDays} options={[['7','Last 7 days'],['30','Last 30 days'],['90','Last 90 days']]}/>}</div>
    {message&&<div className="notice" role="status">{message}</div>}
    <TabsContent value="overview">{loaded&&!metrics.length&&<div className="setup-banner"><div><strong>{data.connections.apple?.configured?'Waiting for available reports.':'Your dashboard is ready for data.'}</strong><p>{data.connections.apple?.configured?'Apple reporting is connected. First reports can take 24–48 hours after activation.':'Connect Apple reporting to see real activity here.'}</p></div><button className="button" onClick={()=>setTab('sources')}>{data.connections.apple?.configured?'View connections':'Set up connections'}<ArrowUpRight size={16}/></button></div>}
    <div className="metrics-grid">{cards.map(c=><section className="metric-card" key={c.label}><div className="metric-label">{c.label}<c.icon size={18}/></div><div className="metric-number">{fmt(c.value)}</div><p>{c.detail}</p></section>)}</div>
    {appId==='all'&&data.apps.length>0&&<section className="panel portfolio-panel"><div className="section-heading"><div><p className="eyebrow">APP PORTFOLIO</p><h2>Performance by app</h2></div></div><Table><TableHeader><TableRow><TableHead>Application</TableHead><TableHead>Downloads</TableHead><TableHead>Listing views</TableHead><TableHead>Last sync</TableHead></TableRow></TableHeader><TableBody>{data.apps.map(app=>{const sum=(metric:string)=>{const rows=metrics.filter(r=>r.appId===app.id&&r.metric===metric);return rows.length?rows.reduce((n,r)=>n+r.value,0):undefined;};return <TableRow key={app.id}><TableCell><button className="app-link" onClick={()=>setAppId(app.id)}>{app.name}<ArrowUpRight size={14}/></button></TableCell><TableCell>{fmt(sum('first_downloads'))}</TableCell><TableCell>{fmt(sum('page_views'))}</TableCell><TableCell>{when(app.lastSync)}</TableCell></TableRow>;})}</TableBody></Table><p className="fine">Totals include available reports only. Apps with no report show “—”, not zero.</p></section>}
    <div className="analysis-grid"><section className="panel"><div className="section-heading"><div><p className="eyebrow">ACQUISITION</p><h2>Downloads over time</h2></div><span className="tag">Daily · UTC</span></div>{series.length?<><div className="bar-chart" role="img" aria-label="Daily first-time downloads">{series.map(s=><div className="bar-column" key={s.day} title={`${s.day}: ${s.count}`}><span>{s.count}</span><div className="bar" style={{height:`${Math.max(2,s.count/Math.max(1,...series.map(r=>r.count))*150)}px`}}/><small>{s.day.slice(5)}</small></div>)}</div><p className="fine">Only reported dates are shown. Missing dates are not treated as zero.</p></>:<NoData title="Your first report starts the story">No download data is available for this period yet. Apple reports can take 24–48 hours to arrive after activation.</NoData>}</section>
    <section className="panel"><div className="section-heading"><div><p className="eyebrow">DISCOVERY</p><h2>Where downloads start</h2></div></div>{channels.length?<div className="channel-list">{channels.map(c=><div key={c.source}><span>{c.source}</span><strong>{fmt(c.count)}</strong></div>)}</div>:<NoData title="Sources will appear here">Compare App Store Search, browsing, and referrals once reports are connected.</NoData>}<p className="fine">Search includes Apple Search Ads. This does not measure exact app-name search ranking.</p></section></div>
    <section className="website-strip"><div className="website-icon"><Globe2/></div><div><h2>ayncode.com</h2><p>Website traffic stays separate from App Store downloads.</p></div><div><strong>{fmt(total('download_clicks'))}</strong><span>App Store button clicks</span></div><div><strong>{fmt(total('website_page_views'))}</strong><span>Website page views</span></div></section><p className="fine footnote"><ShieldCheck size={15}/>Apple reports are aggregated and delayed. Privacy thresholds may hide low-volume activity. “—” means unavailable, not zero.</p></TabsContent>
    <TabsContent value="subscribers"><section className="panel"><div className="section-heading"><div><p className="eyebrow">{subscriberSupported?'GETREEP PLUS':data.apps.find(a=>a.id===appId)?.name}</p><h2>Your subscriber accounts</h2><p className="subtitle">Names when available; account IDs when they aren’t.</p></div>{subscriberSupported&&<Picker label="Subscription environment" value={environment} onChange={setEnvironment} options={[['PRODUCTION','App Store purchases'],['SANDBOX','TestFlight / sandbox'],['UNKNOWN','Unknown environment']]}/>}</div>{subscriberSupported&&<div className="search-row"><Search size={18}/><input aria-label="Search subscribers" placeholder="Search name, account ID, or status" value={query} onChange={e=>setQuery(e.target.value)}/></div>}
    {!subscriberSupported?<NoData title="Subscriber connection needed for this app">Apple reports do not include customer names. Connect this app’s subscription backend separately. Getreep records are never shown as this app’s subscribers.</NoData>:data.subscriberError?<div className="notice" role="alert">{data.subscriberError} App access is unaffected.</div>:!data.connections.subscribers?.configured?<NoData title="Connect your subscription records">Getreep already records Plus access through RevenueCat and Supabase. A secure read-only connection is needed before this list can load.</NoData>:!subscribers.length?<NoData title={query?'No matching accounts':'No subscriber accounts in this environment'}>{query?'Try a different name or account ID.':'Production and sandbox purchases are kept separate.'}</NoData>:<Table><TableHeader><TableRow><TableHead>Subscriber</TableHead><TableHead>Plan</TableHead><TableHead>Access</TableHead><TableHead>Access until</TableHead></TableRow></TableHeader><TableBody>{subscribers.map(s=><TableRow key={s.id}><TableCell><strong>{s.name||'Unnamed account'}</strong><span className="account-id">{s.id}</span></TableCell><TableCell>{s.product}</TableCell><TableCell><span className={`tag ${s.status==='Active access'?'active':''}`}>{s.status}</span></TableCell><TableCell>{when(s.expiresAt)}</TableCell></TableRow>)}</TableBody></Table>}
    {subscriberSupported&&<><p className="fine">Linked-account access, not unique paying people. Guest purchases and deleted accounts may be absent; aliases can represent the same purchase. Renewal, trial, and billing status are not inferred from access alone.</p><p className="fine">Last checked: {when(data.subscriberFetchedAt)}. Names come from Getreep profiles, not Apple reports. No trips, documents, or mailbox data are collected here.</p></>}</section></TabsContent>
    <TabsContent value="sources"><div className="connections-grid">{[{key:'apple',title:'App Store Connect',icon:Download,text:'Downloads, listing views, impressions, and discovery sources.'},{key:'subscribers',title:'Getreep Plus',icon:Users,text:'Current linked subscriber accounts from existing subscription records.'},{key:'website',title:'ayncode.com',icon:Globe2,text:'Aggregate website views and app-specific App Store button clicks.'}].map(c=><section className="panel connection" key={c.key}><c.icon size={24}/><div className="connection-title"><h2>{c.title}</h2><span className="tag">{data.connections[c.key]?.configured?'Configured':'Setup needed'}</span></div><p>{c.text}</p><p className="fine">{data.connections[c.key]?.message||'Not connected yet.'}</p><p className="fine">{when(data.connections[c.key]?.lastSync)}</p>{c.key==='apple'?<button className="button" disabled={busy||!data.connections.apple?.configured} onClick={()=>void syncApple()}>Sync Apple reports</button>:c.key==='subscribers'?<button className="button secondary" onClick={()=>setTab('subscribers')}>View subscribers<ArrowUpRight size={16}/></button>:<a className="button secondary" href="https://ayncode.com" target="_blank" rel="noreferrer">Open website<ExternalLink size={15}/></a>}</section>)}</div>
    <section className="panel setup-guide"><h2>Connect once. Keep the data private.</h2><div className="guide-grid"><div><h3>01 / Apple reporting</h3><p>Add a dedicated App Store Connect reporting key securely to the server settings. Then use Sync Apple reports. Apple’s first reports can take 24–48 hours.</p><a href="https://appstoreconnect.apple.com/access/integrations/api" target="_blank" rel="noreferrer">Open Apple API settings<ExternalLink size={14}/></a></div><div><h3>02 / Subscriber accounts</h3><p>Connect the Getreep Supabase project with server-only credentials. This dashboard only reads subscription records and profile names; it never changes purchases.</p></div><div><h3>03 / Website reports</h3><p>When enabled, AyNcode records aggregate page views and app-specific App Store link clicks. No visitor profiles, IP addresses, or tracking cookies are saved. Counting starts when this feature is enabled; it is not a historical visitor count.</p></div></div><p className="fine">Never paste API keys into chat or upload them as reports. This dashboard uses your existing AyNcode admin login.</p></section>
    <section className="panel import-panel"><div><h2>Import daily totals</h2><p>Use the template for exported analytics. Choose an individual app above. Counts are saved by app, date, metric, and source; repeating an import replaces the matching totals.</p><p className="fine">Normalized CSV—not an unmodified Apple report. Omit missing or privacy-suppressed counts; don’t enter zero.</p></div><div className="import-actions"><a className="button secondary" href="/admin/getreep/metrics-template.csv" download>Download CSV template</a><label className={`button ${importing?'disabled':''}`}><FileUp size={16}/>{importing?'Importing…':'Import CSV'}<input aria-label="Import CSV" type="file" accept=".csv,text/csv" disabled={importing} onChange={e=>{void upload(e.target.files?.[0]);e.target.value='';}}/></label></div></section></TabsContent>
    </Tabs><footer>AyNcode App Insights<span>Owner-only · No customer-facing app changes</span></footer></main></div>;
}
